package backend;


import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

// Generated by https://www.jsonschema2pojo.org/
public class RegisterData {
	@SerializedName("username")
	@Expose
	private String username;
	@SerializedName("email")
	@Expose
	private String email;
	@SerializedName("password")
	@Expose
	private String password;
	@SerializedName("university")
	@Expose
	private String university;
	
	public String getUsername() {
	return username;
	}
	
	public void setUsername(String username) {
	this.username = username;
	}
	
	public String getEmail() {
	return email;
	}
	
	public void setEmail(String email) {
	this.email = email;
	}
	
	public String getPassword() {
	return password;
	}
	
	public void setPassword(String password) {
	this.password = password;
	}
	
	public String getUniversity() {
		return this.university;
	}
	
	public void setUniversity(String university) {
		this.university = university;
	}

}